name: Bug Report
description: You think somethings is broken
title: "[Bug]: "
labels: [ "bug" ]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues and checked the recent builds/commits
          required: true
  - type: textarea
    id: what-did
    attributes:
      label: Issue
      description: You can describe the bug here as well as add your used images if you want.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs
      render: Shell